kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-nextcloud
  template:
    metadata:
      labels:
        app: example-nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:20.0.4-apache
          resources: {}
          volumeMounts:
            - mountPath: /etc/apache2/ports.conf
              name: nextcloud-config
              subPath: ports.conf
            - mountPath: /etc/apache/sites-available/000-default.conf
              name: nextcloud-config
              subPath: apache.conf
      volumes:
        - name: nextcloud-config
          configMap:
            name: nextcloud-config
