kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nextcloud-sample
spec:
  to:
    kind: Service
    name: nextcloud-sample
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
